Accounts/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'Accounts'
urlpatterns = [
    
    path('signup/',views.signup, name='signup'),

    path('logout/', views.custom_logout_view, name='custom_logout'),
    path('custom_login_view/',custom_login_view,name= 'custom_login_view')
    
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Accounts.urls',namespace='accounts')),
    path('',include('dashboard_moral_person.urls',namespace='dashboard_m')),
    path('',include('dashboard_normal_person.urls',namespace='dashboard_n')),
    path('home/',include('report.urls',namespace='home'))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'report'
urlpatterns = [
    
    path('list/',views.list, name='list'),
    path('<str:slug>',views.details, name='details'),

    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="ar"  dir="rtl" lang="zxx" style="height: 100%;">
  <head>
    <meta charset="utf-8" />
    {% comment %} <meta http-equiv="x-ua-compatible" content="ie=edge" /> {% endcomment %}
    <title>تحقيق علني</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8">
    <meta http-equiv="Content-Language" content="ar">
    <meta name="direction" content="rtl" dir="rtl">
    
    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png" />
    <link
    href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap"rel="stylesheet"/>
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
  </head>

  <body>
    <!--[if lte IE 9]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please
        <a href="https://browsehappy.com/">upgrade your browser</a> to improve
        your experience and security.
      </p>
    <![endif]-->

    <!-- header-start -->
    <header>
      <div class="header-area">
        <div id="sticky-header" class="main-header-area">
          <div class="container-fluid">
            <div class="header_bottom_border">
              <div class="row align-items-center">
               
                <div class="col-xl-3 col-lg-2">
                  <div class="logo">
                    
                  </div>
                </div>
                <div class="col-xl-6 col-lg-7">
                  <div class="main-menu d-none d-lg-block">
                    
                  </div>
                </div>
                <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                  <div class="Appointment">
                    <div class="phone_num d-none d-xl-block">
                      <a class="boxed-btn3" href="{% url 'accounts:custom_login_view' %}">تسجيل الدخول</a>
                    </div>
                    <div class="d-none d-lg-block">
                      
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <div class="mobile_menu d-block d-lg-none"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    
    {% block content %}
        
    {% endblock content %}
        
   
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>

    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>

    <script src="js/main.js"></script>
  </body>
</html>