project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('Accounts.urls',namespace='accounts')),
    path('',include('dashboard_moral_person.urls',namespace='dashboard_m')),
    path('',include('dashboard_normal_person.urls',namespace='dashboard_n')),
    path('home/',include('report.urls',namespace='home'))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
   
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'report'
urlpatterns = [
    
    path('list/',views.list, name='list'),
    path('<str:slug>',views.details, name='details'),

    
]

report/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class Reports(models.Model):
    state = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    municipality = models.CharField(max_length=100)
    classification_of_the_establishment = models.CharField(max_length=300)
    decree_number = models.IntegerField()
    date_of_decree_issuance = models.DateField()
    public_inquiry_number = models.IntegerField()
    date_of_public_inquiry_issuance = models.DateField()
    duration = models.CharField(max_length=100)
    start_date_of_the_duration = models.DateField()
    end_date_of_the_duration = models.DateField()
    request_of_mr = models.CharField(max_length=75)
    exploitation_of_the_classified_establishment = models.CharField(max_length=75)
    located_in = models.CharField(max_length=75)
    designation = models.CharField(max_length=75)
    photo = models.ImageField(upload_to='photo/',null = True, blank=True)
    slug = models.SlugField(blank=True,null=True)
    
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.id)
        super(Reports,self).save(*args, **kwargs)
        
class Comment(models.Model):
    name = models.CharField(max_length=50, blank=True,null = True)
    email = models.EmailField(max_length=254, blank=True,null = True)
    titl = models.ForeignKey(Reports, related_name=("aplly_job"), on_delete=models.CASCADE)
    comment = models.TextField(blank=True,null = True)

report/forms.py
from django import forms
from .models import Comment

class apply_form(forms.ModelForm):
    class Meta:
      model = Comment
      fields = ['name','email','comment']
      labels = {
            'name': '',
            'email': '',
            'comment': '',
        }
    def __init__(self, *args, **kwargs):
        super(apply_form, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'placeholder': 'الاسم'})
        self.fields['email'].widget.attrs.update({'placeholder': 'البريد الإلكتروني'})
        self.fields['comment'].widget.attrs.update({'placeholder': 'رأيك'})

report/views.py
from django.forms import SlugField
from django.shortcuts import render
from .models import Reports
from .forms import apply_form
# Create your views here.
def list(request):
    list = Reports.objects.all()
    
    return render(request,'job_list.html',{'list':list})

def details(request,slug):
    detail = Reports.objects.get(slug=slug)
    if request.method == 'POST':
        form = apply_form(request.POST,request.FILES)
        if form.is_valid:
            my_form = form.save(commit=False)
            my_form.titl = detail
            my_form.save()
           
            
            
    else :
        form = apply_form()
        
    context = {'detail':detail,'form':form}
    return render(request,'job_details.html',context)

   

report/templates/job_details.html
{% extends "base.html" %}
{% load bootstrap4 %} 
{% block content %}
<style>
  .rtl {
    direction: rtl;
    text-align: right;
  }
</style>
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3></h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area" >
  <div class="container" >
    <div class="row" >
      <div class="col-lg-8"  style="width: 80%; margin: auto;">
       
        <div class="descript_wrap white-bg" style="border: solid;">
          <div class="single_wrap">
            <h4>ولاية: {{detail.state}}</h4>
            <h4>دائرة: {{detail.district}}</h4>
            <h4>بلدية: {{detail.municipality}}</h4>
            <p>
              منشأة مصنفة من الصنف {{detail.classification_of_the_establishment}}
            </p>
            <p>يهني السيد رأيس المجلس الشعبي البلدي عين تموشنت إلى علم الجمهور</p>
            <p>
                         وفقا للمنشور التنفيذي رقم {{detail.decree_number}}و المؤرخ في {{detail.date_of_decree_issuance}}
            </p>
            <p>
              وتبقاً لقرار فتح التحقيق العلني رقم {{detail.public_inquiry_number}} المؤرخ في{{detail.date_of_public_inquiry_issuance}}
            </p>
            <p>
               سيشرع في التحقي العلني لمدة أقصاها {{detail.duration}} يوماً ابتداء من  {{detail.start_date_of_the_duration}}
            </p>
            <p>
              و إلى {{detail.end_date_of_the_duration}} لطلب السيد {{detail.request_of_mr}}
            </p>
            <p>
               باستغلال المنشأة المصنفة {{detail.exploitation_of_the_classified_establishment }} الكائنة ب {{detail.located_in}} وفي
            </p>
            <p>
              خلال مدة التحقيق يعين السيد {{detail.designation }} كمندوب محقق لاستلام
            </p>
            <p>
              الملاحظات حول التأثيرات السلبية و الإيجابية المتعلقة بالمشروع وكل شخص لديه اقتراحات أو ملاحظات أو ضد المشروع يتصل بالبلدية أين سيجد سجلاً مفتوحاً لهذا الغرض 
            </p>
          </div>
          
          
        <div class="apply_job_form white-bg">
          <div class="apply_job_form white-bg">
            <h4>أرسلك رأيك في هذا التحقيق</h4>
            
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                  <button class="boxed-btn3 w-100" type="submit">أرسل الأن</button>
                {% endbuttons %}
            </form>
        </div>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %} 

report/templates/job_list.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>عدد التحقيقات +{{list|length}} </h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">

  <div class="container">
    
    <div class="job_lists m-0">
   
      <div class="row" style="margin-left: 0; margin-right: 0;">
        <div class="col-lg-12 col-md-12">
          <div class="single_jobs white-bg d-flex justify-content-between flex-column">
            
            <!-- عنوان قوانين -->
           
            
            <!-- الأزرار -->
            <div class="d-flex justify-content-between align-items-center mt-3">
              <div>
                <a href="{% static 'img/06-198.pdf' %}" class="boxed-btn3">المرسوم التنفيذي 06-198</a>
              </div>
              
              <div class="text-center">
                <a href="{% static 'img/07-144.pdf' %}" class="boxed-btn3">المرسوم التنفيذي 07-144</a>
              </div>
              
              <div class="text-right">
                <a href="{% static 'img/167-22.pdf' %}" class="boxed-btn3">المرسوم 22-167</a>
              </div>
            </div>
            
          </div>
        </div>
      </div>
        {% for lists in list %}
            
            
        <div class="col-lg-12 col-md-12">
          <div class="single_jobs white-bg d-flex justify-content-between">
            <div class="jobs_left d-flex align-items-center">
              
              {% if lists.photo %}
                <div class="thumb">
                  <img src="{{lists.photo.url}}" alt="" />
                </div>
              {% else %}
                <div class="thumb">
                  <img src="{% static 'img/ejr.jpg' %}" alt="" width="82" height="82"/>
                </div>
              {% endif %}
              <div class="jobs_conetent">
                <a href="{% url 'home:details' lists.slug %}"><h4>تحقيق علني</h4></a>
                <div class="links_locat d-flex align-items-center">
                  <div class="location">
                    <p><i class="fa fa-map-marker">{{lists.located_in}}</i></p>
                  </div>
                 
                </div>
              </div>
            </div>
            <div class="jobs_right">
              <div class="apply_now">
                <a href="{% url 'home:details' lists.slug %}" class="boxed-btn3">عرض التفاصيل</a>
              </div>
              <div class="date">
                <p>{{lists.end_date_of_the_duration}}إلى{{lists.start_date_of_the_duration}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="pagination_wrap"></div>
        </div>
      </div>
    </div>
    {% endfor %}
    

  </div>
</div>
<!-- job_listing_area_end  -->

<!-- footer start -->
{% endblock content %}